### ISSUE TITLE
Plugin crashes after vscode update to 1.52.0

### ISSUE THREAD

**Issue by Codemonkey1973** [JohnstonCode/svn-scm#1199]
- VSCode Version:1.52.0
- OS Version:Xubuntu 20.04 (Guest OS in VirtualBox)
- Extension Version:2.13.5
- System Language:English
- SVN Version:1.13.0 (r1867053)

## Issue ##
Plugin crashes after each action. It worked perfectly before the vscode update.

## Steps to Reproduce ##

1.Commit some changes
2.Extension host terminated unexpectedly

## SVN Output ##
[www]$ svn commit go/private/app/common/sidebar.html -m 'svn plugin test' --depth empty
[www]$ svn stat --xml --no-ignore --ignore-externals
![Screenshot_2020-12-17_09-13-00](https://user-images.githubusercontent.com/34962558/102467799-a2516b80-4048-11eb-84b8-6361a426ec90.png)

**Comment by JohnstonCode** [comment]
Unable to reproduce.

**Comment by mattiagalati** [comment]
Same for me,

- VSCode Version: 1.55.1
- OS Version: Windows_NT x64 10.0.19042
- Extension Version: 2.13.5
- System Language: Italian
- SVN Version: 1.14.0

## Issue ##
I use the SVN extensione with TortoiseSVN extension in order to complete context actions to checkout, lock, commit files inside VSCode. Randomly, locking a file or commiting, Tortoise complete correctly the action but VSCode show the same alert as in screenshot posted by @Codemonkey1973

## Steps to Reproduce ##

1. Open VSCode, lock some files, commit some changes
2. Extensions Host crashes

## SVN Output ##
```
[..]$ svn: E200009: Could not display info for all targets because some targets don't exist
[..]$ svn stat --xml --no-ignore --ignore-externals
[..]$ svn stat --xml --no-ignore --ignore-externals
[..]$ svn info --xml c:\Project\iirf.ini
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn info --xml
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn info --xml
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn info --xml
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn info --xml
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn info --xml
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn info --xml
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn info --xml
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn: E170013: Unable to connect to a repository at URL 'http://svn.mydomain.com/svn/Repository'
[..]$ svn: E000002: Could not find the requested SVN filesystem
[..]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[..]$ svn info --xml
```

## Screenshots ##

![Code_3x5DFELNBS](https://user-images.githubusercontent.com/6606297/114151890-e7fab280-991d-11eb-94eb-ba27ea2405ab.png)
