### ISSUE TITLE
Extension "forgets" credentials

### ISSUE THREAD

**Issue by IZSkiSurfer** [JohnstonCode/svn-scm#1601]
With the latest update of your extension you get asked for the svn credentials every time you restart/reload VSCode (working with remote workspace via SSH).
Please provide a way to store the crendentials somewhere so the extension acts as in the past.

Thank you

**Comment by JohnstonCode** [comment]
Thanks for the report. I will investigate

**Comment by JohnstonCode** [comment]
@TylerLeonhardt is the  SecretStorage API in-memory only or is it persisted?

**Comment by TylerLeonhardt** [comment]
It's persisted. @IZSkiSurfer can you tell us more about the platform you're running on? Also, what version of VS Code are you running on? There are some troubleshooting steps here:
https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues

**Comment by IZSkiSurfer** [comment]
Thanks so far.

It's strange.. Now it works. I tried it twice.
Before I reported the issue I tried it several times and every time after "Developer: Reload Window" it kept asking for the subversion credentials.

Haven't done any restart or anything since then except running "cmdkey /list"

My colleague had the problem that he wasn't even able to login after the update... I'll text him he should try again.

I'll keep the ticket open till monday in case it happens again. By inspecting your code it should work ;)

**Comment by TylerLeonhardt** [comment]
For what it's worth, the credential storage mechanism on Windows will be changing in the next stable version of VS Code and you should have a lot more stability. That's projected for the first week of July....... or, you could try https://code.visualstudio.com/insiders to try it out now in this side-by-side install :) 

This is because VS Code will no longer use [keytar](https://github.com/atom/node-keytar) for the abstraction layer that @JohnstonCode uses in this extension.

**Comment by IZSkiSurfer** [comment]
Okay seems to work stable.
And dohh... my colleague entered the wrong credentials.
