### ISSUE TITLE
SVN is not available in your PATH

### ISSUE THREAD

**Issue by bishnuprasad08** [JohnstonCode/svn-scm#32]
- VSCode Version:1.17.2
- OS Version:Windows 10 
- Extension Version:PHP
- System Language:

SVN is not available in your PATH. svn-scm is unable to run!

I am getting this error in visual studio code .I have already set my SVN path in environmental variables. Still getting this issues .

Steps to Reproduce:

1.Install the extension .
2.Open any project .It is showing on top

**Comment by JohnstonCode** [comment]
What output do you get if you run "svn info" in the folder you are trying to open?

**Comment by s-martin** [comment]
Do you use TortoiseSVN? If yes, did you install TortoiseSVN with Command Line Tools (i.e. `C:\Program Files\TortoiseSVN\bin` should contain a **svn.exe**)

**Comment by luanmm** [comment]
Why should it depend specificly in TortoiseSVN? I already have another SVN client tool in my path that I can run using any command-line, as SVN always uses a standard program "svn.exe" in Windows, and can't get it to work with svn-scm aswell, for the same reason.

**Comment by JohnstonCode** [comment]
What output do you get if you run "svn --version" in the folder you are trying to open?

**Comment by luanmm** [comment]
For me, it gives this output:

```
svn, version 1.9.5 (r1770682)
   compiled Dec  1 2016, 13:58:25 on x86/x86_64-microsoft-windows6.1.7600

Copyright (C) 2016 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.8 (compiled with 1.3.8)
  - handles 'http' scheme
  - handles 'https' scheme

The following authentication credential caches are available:

* Wincrypt cache in C:\Users\<user>\AppData\Roaming\Subversion
```

**Comment by JohnstonCode** [comment]
Thanks for getting back to me so fast.

Issues like this should be fixed in the next release and if not give a more accurate error message.

**Comment by luanmm** [comment]
You're welcome, @JohnstonCode. Thanks for answering that fast, too, and for all your work in this extension. If you need more details, feel free to ask.

Just a little question, if I may ask: do you have any plans in using "git-svn" someday as an alternative for an SVN client? It couldn't mimic everything that SVN does? These questions are somehow important because there are some developers who prefer to work with Git (as it is widely used nowadays) and SVN is used only for compatibility with older projects/ecosystems. Anyway... do you think this is a possibility for the future?

**Comment by Arwalk** [comment]
I don't think this should be the responsability of this extension. git-svn is a git command, not a svn one.

**Comment by luanmm** [comment]
@Arwalk from this point of view, I agree. But think that way: if `git-svn` can do everything SVN does (or better, can do everything the user may do from the VSCode interface), there is no point to have two extensions co-existing with the same functionality.

My thought is that a lot more VSCode users use Git than SVN. And they already have Git client installed. So why - if `git-svn` could be used - they must have tools like TortoiseSVN or other SVN clients to use this extension? That's my point here.

**Comment by Arwalk** [comment]
@luanmm someone using git-svn wants to use git, and just interface on svn when needed. Supporting git-svn through another extension (that could rely on svn-scm, maybe?) or through an update of git support in vscode seems way more coherent.

Also, i don't see where you understood that the extension relies on tortoiseSVN. The extension relies on the svn binary of your own setup. I.e: i use svn-scm on linux, and there is no TortoiseSVN on linux.

**Comment by luanmm** [comment]
@Arwalk sometimes people don't use Git or SVN because they want, but because it is needed. My point is just to simplify things here.

The `git-svn` tool has no point for Git repositories. It is a wrapper inside its client to make it capable of dealing with SVN repositories. And deal with SVN repositories is the point of this extension. That's the link.

My first comment was a bit awkward, indeed. In Windows, TortoiseSVN is a possibility, when installed with the command-line tools. That's where I messed up with things to talk about this client specificly. But my problem is that I have another client in my PATH which I can use in a command-line without any problems, but the extension can't recognize it as an SVN client. For that reason, I concluded that TortoiseSVN may be some kind of requirement in Windows environments.

**Comment by s-martin** [comment]
**tl'dr: Do not support git-svn**

@luanmm From my point of view svn-svm shouldn't provide an inteface to git-svn, because that would be using a SVN extension to utilitze a git command to connect to a SVN repo. That doesn't make sense to me and I don't see how this is a simplification.

At this point you can already use the Git extension to use git-svn to connect to a SVN repo. Although you have to use the git-svn command on the terminal.

When there was no SVN extension for VSCode available before @JohnstonCode started this extension, I used the Git extension together with git-svn to work with a big SVN project. It works fairly well, but with two exceptions:

- With this workflow it is not possible to SVN update, if you have changes in your workspace. Not a big issue for experienced Git users (just use stash..), but for SVN users this is a PITA and conflicts with the workflow many SVN users do.
- On this particular SVN repo we have a pre-commit hook, which checks, if your comment contains a JIRA key. However, with the Git extension + git-svn you could easily Git commit, but if you want to dcommit to the SVN repo, it would fail and then you would have to undo the Git commit etc.

**Comment by luanmm** [comment]
@s-martin thanks for the information. This clarify some things.

I have just asked for any plans regarding `git-svn`, but I never told that it was something this extension MUST provide. I don't even know if the tool has support for everything it would need to be able to do the things SVN clients do, as I stated before.

About your tip regarding Git extension + git-svn, it is not really a solution. If I need to do things from the command-line, what is the point to have any extension at all? But maybe this integration is a concern for the team who develop Git extension for VSCode, indeed.

Thanks for the answers.

**Comment by JohnstonCode** [comment]
@luanmm my plan for this extension is to not need to use the terminal at all for any SVN workflow. 

The limiting factor at the moment is my time.

**Comment by luanmm** [comment]
@JohnstonCode yep, sure. It seems to be a great job till now. Please don't take any comment as a criticism. It was just a discussion about possibilities.

I'm sure it already fills a gap in a lot of scenarios and have potential to be a great extension for more in the near future. Congratulations for the initiative!

**Comment by magic-k** [comment]
@s-martin Isn't a rebase the aquivalent so svn update?
@luanmm If you checkout a svn repository with git svn clone, you have a git repository where you want to use git commands. So i think it falls in the git extension to provide git svn. Maybe as an extension to the git extension.
I have a lot of legacy projects in an svn repository. Converting it to a git repository or even use git-svn is not really an option. So i'm thankful for this extension which make vscode a ful fledged IDE for my developemenmt needs. 
For new projects i will use git.

**Comment by JohnstonCode** [comment]
Should be working in v1.0.1
