### ISSUE TITLE
Extension appears to hang after start up

### ISSUE THREAD

**Issue by RayDeCampo** [JohnstonCode/svn-scm#462]
- VSCode Version: 1.30.2
- OS Version: Windows 10 (10.0.17134)
- Extension Version: 1.47.0
- System Language: English
- SVN Version: 1.8.14

## Issue ##

The subversion commands run by the extension never complete.

Upon starting VS Code, the extension correctly determines the state of the local files (I assume via svn status).  After that however, any requested changes via the extension result in the cylon progress bar.

## Steps to Reproduce ##

1.  Start VS Code
2.  Perform any action using the extension, e.g. add a file, refresh the source control panel, expand a repository in the subversion panel.

## SVN Output ##
```
Using svn "1.8.14" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[webcm-fsep]$ svn cat c:\eng\projects\path\to\a\file\that\was\open.sql
[webcm-fsep]$ svn info --xml
[webcm-fsep]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[webcm-fsep]$ svn info --xml
[webcm-fsep]$ svn cat -r HEAD svn+ssh://my.svn.host/svn/path/to/file/trying/to/view/diffs/on.sh
```

## Screenshots ##

![image](https://user-images.githubusercontent.com/10577771/51488588-f461b780-1d73-11e9-952e-8ff2e268a652.png)

**Comment by JohnstonCode** [comment]
Are you using a VPN?

**Comment by RayDeCampo** [comment]
No, everything is available on the LAN.  I have no issues using TortoiseSVN outside of VS Code.

**Comment by smeesseman** [comment]
I have the same issue.  Starting VS Code everything works fine, but the first touch of anything results in the never ending progress bar and multiple svn.exe processes left running in the background.  Running all latest version as I am testing Code and SCM integration to migrate my entire environment from Eclipse.  Thankfully, at lest you have made this extension, without it Code wouldnt be an option for me.  So thank you!!!!!!!!!  But, I'd love for it to work after I start Code :)

This is my SVN console after opening Code, then opening a Help.js file and making an edit:  (all these commands finish quickly when run manually in a shell and exit fine).  The extension is clearly watching, but the panel that shows local changes does not show the change, and the progress bar never stops spinning, plus the leftover svn.exe processes running until Code is shut down.  Same thing happens when trying to expand a repository node under "Repositories" (as OP stated).

[LegalTrax]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[LegalTrax]$ svn info --xml c:\Projects\LegalTrax\src\ui\app\desktop\src\view\login\Login.js
[LegalTrax]$ svn cat c:\Projects\LegalTrax\src\ui\app\desktop\src\view\login\Login.js
[LegalTrax]$ svn info --xml c:\Projects\LegalTrax\src\ui\app\desktop\src\view\help\Help.js
[LegalTrax]$ svn cat c:\Projects\LegalTrax\src\ui\app\desktop\src\view\help\Help.js
[LegalTrax]$ svn info --xml c:\Projects\LegalTrax\src\ui\app\desktop\src\view\login\Login.js
[LegalTrax]$ svn cat c:\Projects\LegalTrax\src\ui\app\desktop\src\view\login\Login.js
[LegalTrax]$ svn info --xml c:\Projects\LegalTrax\src\ui\app\desktop\src\view\help\Help.js
[LegalTrax]$ svn cat c:\Projects\LegalTrax\src\ui\app\desktop\src\view\help\Help.js
[LegalTrax]$ svn log -r HEAD:1 --limit=50 --xml -v svn+ssh://*****************/repo/trunk/LegalTrax/src/ui/app/desktop/src/view/help/Help.js

**Comment by smeesseman** [comment]
The problem for me was the svn+ssh protocol.  As soon as I opened up a port for svnserve on my server, and using svn protocol instead of svn+ssh from client, everything is working great in Code now.  I imagine this might not be an option to do for most people, and I would much rather use SSH, if this could be looked at, I would greatly appreciate it!  But for now, Im good!  Thank you for the sweet extension and time spent

**Comment by RayDeCampo** [comment]
I had not realized that the Output window was affected by the pulldown.  So I do indeed have SVN Output.  Apologies for the incomplete report.  Here's the content of the SVN output when trying to view differences:

```
Using svn "1.8.14" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[webcm-fsep]$ svn cat c:\eng\projects\path\to\a\file\that\was\open.sql
[webcm-fsep]$ svn info --xml
[webcm-fsep]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[webcm-fsep]$ svn info --xml
[webcm-fsep]$ svn cat -r HEAD svn+ssh://my.svn.host/svn/path/to/file/trying/to/view/diffs/on.sh
```

I have updated the original report as well.

I see you still have the issue marked as needing feedback.  As I mentioned before, I am not using a VPN, everything is on my LAN.  I am not aware of any further requests for information.  If there is anything further you need from me, please let me know.

**Comment by JohnstonCode** [comment]
@RayDeCampo are you still having issues after latest release?

**Comment by RayDeCampo** [comment]
I updated everything to the latest and re-enabled the extension.  Everything is working as advertised.  If I hit an additional issue I will open a new report.  Thanks for getting this taken care of.
