### ISSUE TITLE
SVN doesn't work with Remote-SSH extension

### ISSUE THREAD

**Issue by FractalBoy** [JohnstonCode/svn-scm#561]
- VSCode Version: 1.34.0-insider
- OS Version: Windows 10 / RHEL 7
- Extension Version: 1.48.1
- System Language: English (US)
- SVN Version: 1.9.7

## Issue ##

I am using the new Remote-SSH extension. When I try to use the SVN extension with it, it reports that "There is no data provider registered that can provide view data".

I thought that it may be that I have svn installed in /opt/subversion/bin/svn, but I tried setting svn.path to that path, and it still doesn't work.

I also tried setting it to my TortoiseSVN path, in case it needs to use the executable on the Windows side for some reason. That doesn't work either.

In the developer's console, there is an error "Cannot find module 'original-fs'". I don't know if that is related.

Note that Git works fine.

## Steps to Reproduce ##

1. Install the Remote-SSH extension.
2. Connect to a Linux system
3. Attempt to use the SVN extension after opening a path that is using SVN.

## SVN Output ##
None - no option in the dropdown.

## Screenshots ##

![image](https://user-images.githubusercontent.com/2024233/57186994-0e03b680-6eae-11e9-8b75-b26b3f0c0641.png)

**Comment by FractalBoy** [comment]
I tested this on just Windows and I do not see the same problem. I also don't see the same error in the developer's console.

**Comment by Chuxel** [comment]
VS Code Remote - SSH will run the subversion extension in a remote host that is a standard Node.js runtime instead of Electron.

With this change, the SVN extension now relies on the `original-fs` node module that is only available inside Electron: JohnstonCode/svn-scm#540

To resolve, there's a value passed into extension activation you can use to load `fs` instead of `original-fs` when in the remote context.  You can also attempt to load original-fs and fall back to fs if it errors.

**Comment by JohnstonCode** [comment]
Thanks @Chuxel Ill get that updated

**Comment by edgardmessias** [comment]
@JohnstonCode , add this package: https://www.npmjs.com/package/original-fs
A single pollyfill

**Comment by ScaredyCat** [comment]
Any movement on this yet?

**Comment by FractalBoy** [comment]
It works. Thanks!
