### ISSUE TITLE
macos cant update

### ISSUE THREAD

**Issue by hezhongfeng** [JohnstonCode/svn-scm#653]
- VSCode Version:1.37.0
- OS Version:macos 10.14.6
- Extension Version:1.54.4
- System Language:Simplified Chinese
- SVN Version:1.12.2

## Issue ##
Unable to update
## Steps to Reproduce ##

1. I checkout my repository use cornerstone 4.1,I can update use cornerstone
2. I open a trunk dir use vscode
3. I can look the changes use plugin

## SVN Output ##
```
Using svn "1.12.2" from "/usr/local/bin/svn"
[20190812_xiaoben]$ svn info --xml
[20190812_xiaoben]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[20190812_xiaoben]$ svn: E170013: Unable to connect to a repository at URL 'https://hezhongfengg@124.235.224.202/svn/icar/00-ProcedureLibrary/01-SourceCode/h5/vfac/branches/20190812_xiaoben'
[20190812_xiaoben]$ svn: E230001: Server SSL certificate verification failed: certificate issued for a different hostname, issuer is not trusted
```

## Screenshots ##
![](https://i.loli.net/2019/08/15/QDJog8USuMTdwhp.png)

**Comment by hezhongfeng** [comment]
![image](https://user-images.githubusercontent.com/12163050/63087585-21cab880-bf85-11e9-8ae5-b23ad7138c4f.png)

**Comment by JohnstonCode** [comment]
try `svn list [repository URL]`  replace [repository URL] with the appropriate URL of your repository

**Comment by hezhongfeng** [comment]
```
➜  trunk svn list https://hezhongfengg@124.235.224.202/svn/icar/00-ProcedureLibrary/01-SourceCode/businessmanagement/trunk
Error validating server certificate for 'https://124.235.224.202:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
 - The certificate hostname does not match.
Certificate information:
 - Hostname: icar-PC
 - Valid: from May 16 04:47:26 2018 GMT until May 13 04:47:26 2028 GMT
 - Issuer: icar-PC
 - Fingerprint: AD:51:C7:B6:60:D6:0F:E9:9B:9C:E4:31:41:3B:B6:33:DF:C0:0D:48
(R)eject, accept (t)emporarily or accept (p)ermanently? 
svn: E170013: Unable to connect to a repository at URL 'https://hezhongfengg@124.235.224.202/svn/icar/00-ProcedureLibrary/01-SourceCode/businessmanagement/trunk'
svn: E230001: Server SSL certificate verification failed: certificate issued for a different hostname, issuer is not trusted
```

**Comment by JohnstonCode** [comment]
Thats your issue then

**Comment by hezhongfeng** [comment]
i use `svn ls`and p

**Comment by 4x10m** [comment]
Hi there,
Just to inform you that sometimes, the permanent option is not available.

I spent a long time investigate this issue and what are the possibilities outside of vscode because its tedious to press t every times for big updates.
So for me the best solution to bypass that is the following alias:
`alias svn="svn --non-interactive --trust-server-cert --trust-server-cert-failures=\"unknown-ca,cn-mismatch,expired,not-yet-valid,other\""`

`❯ svn ls
Erreur de validation du certificat du serveur pour '...' :
 - Le nom d'hôte du certificat ne correspond pas.
 - Le certificat a expiré.
 - Le certificat conduit à une erreur inconnue.
Informations du certificat :
 - nom d'hôte : ...
 - valide de Aug 27 14:05:48 2010 GMT à Aug 24 14:05:48 2020 GMT
 - signataire : ...
 - empreinte : ...
(R)ejet, ou acceptation (t)emporaire ? p
svn: E170013: Unable to connect to a repository at URL '...
svn: E230001: Server SSL certificate verification failed: certificate has expired, certificate issued for a different hostname, and other reason(s)`

May you can do something for that ? May be add an option which spitulate that this may produce security holes ?

Thks

**Comment by hsxrcn** [comment]
I have the same problem，and I use  "svn  ls"，I select  "p" ,  it is work .
