### ISSUE TITLE
not registering changes on file save

### ISSUE THREAD

**Issue by art40100** [JohnstonCode/svn-scm#842]
- VSCode Version:
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299
- Extension Version:
2.10.3
- SVN Version:
Using svn "1.13.0" from "C:\Program Files\TortoiseSVN\bin\svn.exe"

## Issue ##
In vscode the extension is slow to register modified files. It seems to happen randomly - after some time it does register. If I click the button 'Update revision' it shows up instantly. I have set "svn.autorefresh": true, but it does not change anything and it worked previously without it set.

## Steps to Reproduce ##

1. open file, make some changes and save the file

## SVN Output ##
```
[xyz]$ svn cat aaa\frontend\controllers\someFile.php
after some time(randomly) these line appear and then the modification is registered in svn (1):
[xyz]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[xyz]$ svn info --xml
```

**Comment by JohnstonCode** [comment]
Unable to replicate on Linux. Will try tonight on windows

**Comment by bkromhout** [comment]
I'm seeing the same issue as well . Additionally, when I delete a versioned file, I'm no longer prompted whether I want to SVN delete or ignore the now-missing file. Like the OP states, I assume this is because the extension is no longer detecting changes properly.

* VS Code Version:
Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
* Extension Version: 2.10.3
* SVN Version: TortoiseSVN 1.13.1

**Comment by TobiasKrahn** [comment]
I got the same issue. I was able to track it down to the changes made in the extension version 2.9.1.

- VS Code Version:
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
- SVN Version: 1.13.0 (TortoiseSVN 1.13.1)

**Comment by ryanjkelly** [comment]
I also have this issue. Thanks @TobiasKrahn, rolling back to `2.9.0` fixed it!

- Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
- Extension Version: 2.10.3
- SVN Version: 1.13.0 (TortoiseSVN 1.13.1)

**Comment by edgardmessias** [comment]
I think the problem is caused by this line: https://github.com/JohnstonCode/svn-scm/compare/v2.9.0...v2.9.1#diff-95486b2c6aba9f0d786024aaa5e65964R32

Could someone edit the file `"~/.vscode/extensions/johnstoncode.svn-scm-2.10.3/out/watchers/repositoryFilesWatcher.js`, line 19, from `path_1.join(path_1.resolve(root), "**")` to `"**"` and report results?

**Comment by JohnstonCode** [comment]
I will on windows machine now

**Comment by JohnstonCode** [comment]
yeah that fixes it

**Comment by edgardmessias** [comment]
Instead of `path`, you can use RelativePattern: https://code.visualstudio.com/api/references/vscode-api#RelativePattern

**Comment by JohnstonCode** [comment]
still doesn't work with RelativePattern
